### ISSUE TITLE
Use ember-cli-eslint

### ISSUE THREAD

**Issue by BrianSipple** [ember-a11y/issues#2]
With ESLint (and ember-cli-eslint) fast-becoming the de-facto linter, is there any opposition to integrating it into our projects? There’s even a feature in the works to [handle the conversion from JSHint](https://github.com/ember-cli/ember-cli-eslint/pull/91) automatically.

**Comment by ghost** [comment]
We should totally get this installed

**Comment by ghost** [comment]
See https://github.com/ember-a11y/ember-a11y/issues/24 and https://github.com/ember-a11y/ember-a11y/issues/25

**Comment by BrianSipple** [comment]
Ah, I was in `ember-a11y-testing` when I made this, and didn't recall that we had it in `ember-a11y` already. Nice. I'll open up an issue in `ember-a11y-testing`

**Comment by ghost** [comment]
:+1:

**Comment by nathanhammond** [comment]
Confirm, this is the direction we're heading as a community.
